#!/usr/bin/env bash

# Este arquivo pode ser usado para executar comandos dentro do container frontend
# Ex: ./container-frontend ls

source .env

COMMAND=$*

docker exec -it $CONTAINER_FRONT_NAME $COMMAND

NEW_FILES="?? "

GIT_STATUS=`cd $PROJECT_FRONT_DIR && git status -s | grep "$NEW_FILES"`

# Concederá permissão de modificação se tiver novos arquivos
if [[ $GIT_STATUS ]]; then
  ./chown-files.sh $PROJECT_FRONT_DIR
fi
