FROM wyveo/nginx-php-fpm:php80

COPY ./backend /var/www/app/

WORKDIR /var/www/app/

RUN sed -i " \
  s|/usr/share/nginx/html|/var/www/app/public|g; \
" /etc/nginx/conf.d/default.conf

RUN sed -i "s| \$uri/index.html||g;" /etc/nginx/conf.d/default.conf

# Instalação do LibreOffice headless
# RUN apt-get update && apt-get install libreoffice --no-install-recommends -y && apt-get install default-jre -y

# Configuração do cron
RUN apt-get update && apt-get install cron -y
RUN echo "* * * * * cd /var/www/app && php artisan schedule:run >> /dev/null 2>&1" > /etc/cron.d/cron_project
RUN crontab /etc/cron.d/cron_project
