version: '3'

services:
  s_project_back:
    container_name: ${CONTAINER_BACK_NAME}
    build:
      context: .
      dockerfile: Dockerfile-backend
    image: ${CONTAINER_BACK_IMAGE}
    restart: unless-stopped
    ports:
      - ${CONTAINER_BACK_EXTERNAL_PORT}:80
    volumes:
      - ./${PROJECT_BACK_DIR}:/var/www/app
