services:
  database:
    container_name: ${DB_CONTAINER_NAME}
    image: mysql:8
    volumes:
      - ./src/${DB_PROJECT_DIR}/MySQL:/var/lib/mysql
      - ./docker/mysql.conf:/etc/mysql/my.cnf
    ports:
      - ${DB_CONTAINER_EXTERNAL_PORT}:3306
    restart: unless-stopped
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}

  backend:
    container_name: ${BACK_CONTAINER_NAME}
    build:
      context: .
      dockerfile: ./docker/Dockerfile-backend
    image: ${BACK_CONTAINER_NAME}
    restart: unless-stopped
    ports:
      - ${BACK_CONTAINER_EXTERNAL_PORT}:80
    volumes:
      - ./src/${BACK_PROJECT_DIR}:/var/www/app
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf

  frontend:
    container_name: ${FRONT_CONTAINER_NAME}
    build:
      context: .
      dockerfile: ./docker/Dockerfile-frontend
    image: ${FRONT_CONTAINER_NAME}
    restart: unless-stopped
    ports:
      - ${FRONT_CONTAINER_EXTERNAL_PORT}:${FRONT_CONTAINER_EXTERNAL_PORT}
    volumes:
      - ./src/${FRONT_PROJECT_DIR}:/app
    command: /bin/sh -c "yarn && quasar dev"
